version: '3.8'

services:
  zookeeper:
    image: bitnami/zookeeper:3.8
    container_name: prototipo-zookeeper
    ports:
      - "2181:2181"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes

  kafka:
    image: bitnami/kafka:3.5
    container_name: prototipo-kafka
    ports:
      - "9092:9092"     # Clientes internos (Flink)
      - "29092:29092"   # Clientes externos (Python, local)
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_CFG_LISTENERS=INTERNAL://0.0.0.0:9092,EXTERNAL://0.0.0.0:29092
      - KAFKA_CFG_ADVERTISED_LISTENERS=INTERNAL://prototipo-kafka:9092,EXTERNAL://localhost:29092
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
      - KAFKA_INTER_BROKER_LISTENER_NAME=INTERNAL
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper

  flink-jobmanager:
    image: flink:1.16-scala_2.12
    container_name: flink-jobmanager
    command: jobmanager
    ports:
      - "8081:8081"
    volumes:
      - ./jars:/opt/flink/usrlib
    environment:
      - JOB_MANAGER_RPC_ADDRESS=flink-jobmanager
    depends_on:
      - kafka

  flink-taskmanager:
    image: flink:1.16-scala_2.12
    container_name: flink-taskmanager
    command: taskmanager
    volumes:
      - ./jars:/opt/flink/usrlib
    environment:
      - JOB_MANAGER_RPC_ADDRESS=flink-jobmanager
    depends_on:
      - flink-jobmanager

  cassandra:
    image: cassandra:3.11
    container_name: prototipo-cassandra
    ports:
      - "9042:9042"
